version: '3.8'

services:

  backend:
    build: ./practica-backend
    #command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./practica-backend:/usr/src/app
    ports:
      - 8004:8000
    container_name: backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
    depends_on:
      - db
    networks:
      network1:
        ipv4_address: 192.168.48.3


  db:
    image: postgres:15.3
    expose:
      - 5432
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
    networks:
      network1:
         ipv4_address: 192.168.48.2

  frontend:
    build: ./practica-frontend
    depends_on:
      - backend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      network1:
         ipv4_address: 192.168.48.4
    env_file:
      - ./practica-frontend/.env

networks:
  network1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.48.0/24